// import Head from 'next/head'
// import Feedback from '../../../pages/Feedback'
// import Image from 'next/image'
//import { icons } from 'react-icons'
import styles from './Feedback.module.css'
import { FaInstagram, FaTwitter} from "react-icons/fa";
// import {MdCode}  from "react-icons/md";
import {SiLinkedin} from "react-icons/Si";
import {ImMail} from "react-icons/im";
import {FaFacebookSquare} from "react-icons/fa";

// const style = { color: "white", fontSize: "1.5em" }

const Feedback=()=>{
  return (
<>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

<div className={styles.container}>
 <div className={styles.feedbackContainer}>
<button className={styles.feedbackButton}>Feedback</button>
</div>
<div>
<p className={styles.text}>
 Please tell us what do you think, any kind of feedback is highly
  appreciated.
</p>
<textarea className={styles.textarea} placeholder="Your Feedback"></textarea>
<div className={styles.sendFeedbackContainer}>
<button className={styles.sendFeedbackButton}>Send Feedback</button>
  </div>
</div>

<div className={styles.contactUsContainer}>
<button className={styles.contactUs}>Contact Us</button>
</div>
<div>
{/* <div className={styles.icons}>
<div className={styles.box}>
 <img className={styles.icon} src="/mail.png" alt="icon" />
<span className={styles.span}>we will give email@gmail.com</span>
</div> */}
{/* <li className={styles.icon}> */}
{/* <img className={styles.icon} src="/instagram.svg" alt="icon"/>
<img className={styles.icon} src="/linkedin.svg" alt="icon" /> */}
<li className={styles.icon}>
<FaInstagram size="37px" color="#D44638"/>
</li>
<li className={styles.icon}>
  <ImMail size="30px" color="rgb(255,160,122)" />
</li>
<li className={styles.icon}>
  <SiLinkedin size="30px" color="#318ce7"  />
</li>
<li className={styles.icon}>
  <FaTwitter size="30px" color="#00aae4" /> 
</li>
<li className={styles.icon}>
<FaFacebookSquare size="30px" color="#5b92e5"/></li>
</div>
</div>
</>
  )
}
export default Feedback